Controllers/CRMController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp_mvc.Models;
using webapp_mvc.Repository;
namespace webapp_mvc.Controllers;

public class CRMController: Controller
{
    private readonly ApplicationDbContext _db;
     private readonly IRepository<SuperAdmin> _repository;
    //make constructure like typescript
    public CRMController(ApplicationDbContext db,IRepository<SuperAdmin> repository)
    {
        _db = db;
        _repository = repository;
    }
      //Get login page
    public IActionResult Login(){


        return View();
    }
    //Post login page
    [HttpPost,ActionName("Login")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Loginn(string username, string pwd){
        var admin = new SuperAdmin();
        var data = await _repository.GetAllAsync();
        var user = data.FirstOrDefault(u => u.username == username && u.pwd== pwd);

        if(user != null){

            TempData["success"] = "Welcome Home";
            return RedirectToAction("Home");
        }
        else{
            ModelState.AddModelError(string.Empty, "Invalid username or password");
            TempData["error"] = "Invalid username or password, please try again";
            return View();
        }

          
      
    }
    //home page

    public IActionResult Home(){
      IEnumerable<Meida> objMedia = _db.Meidas;

        return View(objMedia);
    }




    //GET
    public IActionResult Index(){
      
                     
       
        
         return RedirectToAction("Login");
       
    
    }
  


 

    //GET MEDIA
  
    public async Task<IActionResult> Upload()
    {
      
        return View();
        
    }
    //POST MEDIA
    // [HttpPost]
    // [ValidateAntiForgeryToken]
    // public async Task<IActionResult> Upload(IFormFile file)
    // {
    //     if (file != null && file.Length > 0)
    //     {
    //         using (var memoryStream = new MemoryStream())
    //         {
    //             await file.CopyToAsync(memoryStream);

    //             var media = new Meida
    //             {
    //                 Filename = file.FileName,
    //                 FileType = file.ContentType,
    //                 FileData = memoryStream.ToArray()
    //             };

    //             _db.Meidas.Add(media);
    //             await _db.SaveChangesAsync();
                 

               
    //         }
    //     }
    //   return RedirectToAction("Index");     
    // }
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Upload(Meida media)
{
    //   if(ModelState.IsValid)
    // {
      
           if (media.File != null && media.File.Length > 0)
            {
       
        using (var memoryStream = new MemoryStream())
        {
            await media.File.CopyToAsync(memoryStream);

            media.Filename = media.File.FileName;
            media.FileType = media.File.ContentType;
            media.FileData = memoryStream.ToArray();
             try{
            _db.Meidas.Add(media);
            await _db.SaveChangesAsync();
            TempData["success"] = "Your product has been uploaded!";
            return RedirectToAction("Home");
             
              }catch(Exception ex){
            TempData["error"] = "An Unhandled error, try again";
               return RedirectToAction("Home");
        }
  }
           
        }
       
    // }
    // else
    //     {
    //          TempData["error"] = "An Unhandled error, try again";
    //            return RedirectToAction("Index");
    //     }
   return View();
    
}

//Get
public async Task<IActionResult> Update(int id){
    
    if(id == 0){
        return NotFound();
    }
  
    var fileFormDb = _db.Meidas.Find(id);
    if(fileFormDb == null){
        return NotFound();
    }
      ViewBag.FileValue = fileFormDb.Filename;

    return View(fileFormDb);
}


//Post
[HttpPost,ActionName("Update")]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Updatee(Meida meida)

{
    
         
         
     if (meida.File != null && meida.File.Length > 0  )
    {
        using (var memoryStream = new MemoryStream())
        {
            await meida.File.CopyToAsync(memoryStream);

            meida.Filename = meida.File.FileName;
            meida.FileType = meida.File.ContentType;
            meida.FileData = memoryStream.ToArray();
           
              _db.Meidas.Update(meida);
              await _db.SaveChangesAsync();
              TempData["success"] = "Your image has been updated!";
              return RedirectToAction("Home");
             
            
      
    }
    }
  
        return View();
    
}
 
   
    // if(ModelState.IsValid)
    // {
    //      try{
                  
    //   _db.Meidas.Update(meida);
    //   await _db.SaveChangesAsync();
    //   TempData["success"] = "Your image has been updated!";

    //        } catch(DbUpdateException ex){
    //              TempData["error"] = "An error occurred while updating the image.";
    //             }


    // }
    
 
    
    // if (meida.File != null && meida.File.Length > 0)
    // {
    //     using (var memoryStream = new MemoryStream())
    //     {
    //         await meida.File.CopyToAsync(memoryStream);

    //         fileFormDb.Filename = meida.File.FileName;
    //         fileFormDb.FileType = meida.File.ContentType;
    //         fileFormDb.FileData = memoryStream.ToArray();

           
    //              _db.Entry(fileFormDb).State = EntityState.Detached; // Detach the fileFormDb entity
    //             _db.Entry(meida).State = EntityState.Modified; // Attach the updated entity
        
    //     }
    // }


//Get
public async Task<IActionResult> Delete(int id ){
    if(id == 0){
        return NotFound();
    }
    var fileFormDb = _db.Meidas.Find(id);
    if(fileFormDb == null){
        return NotFound();
    }
     ViewBag.FileValue = fileFormDb.Filename;
    return View(fileFormDb);
}
[HttpPost,ActionName("Delete")]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Deletee(int id)
{
    var media = await _db.Meidas.FindAsync(id);
    if (media == null)
    {
        return NotFound();
    }

    _db.Meidas.Remove(media);
    await _db.SaveChangesAsync();
    TempData["success"] = "Your image has been deleted!";

    return RedirectToAction("Index");
}


}

Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp_mvc.Models;
using webapp_mvc.Repository;

namespace webapp_mvc.Controllers;

public class HomeController : Controller
{
    // private readonly ILogger<HomeController> _logger;

    // public HomeController(ILogger<HomeController> logger)
    // {
    //     _logger = logger;
    // }
     private readonly ApplicationDbContext _db;
      private readonly IRepository<Meida> _repository;
    //make constructure like typescript
    public HomeController(ApplicationDbContext db, IRepository<Meida> repository)
    {
        _db = db;
        _repository = repository;
    }
         //[FromQuery(Name = "SearchString")]
    public async Task<IActionResult> Index( string searchString)
    {
     if (_db.Meidas == null)
    {
        return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
    }
    var media = from m in _db.Meidas
                select m;

    if (!String.IsNullOrEmpty(searchString))
    {
        media = media.Where(w => w.ProductName.Contains(searchString) || w.Price.ToString() == searchString 
                                                || w.ProductDesc.Contains(searchString) || w.Gender == searchString || w.Filename.Contains(searchString));
    }
    // IEnumerable<Meida> objMedia = _db.Meidas;

        return View(await media.ToListAsync());
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
    // [HttpGet]
    // [ValidateAntiForgeryToken]
    // public async Task<IActionResult> Search(string word)
    // {
    //     var data = await _repository.GetAllAsync();
    //     var wordSearched = data.FirstOrDefault(w => w.ProductName == word || w.Price.ToString() == word 
    //                                              || w.ProductDesc.Contains(word) || w.Gender == word || w.Filename.Contains(word) ) ;

    //      if(wordSearched != null)
    //      {
    //         return (IActionResult)wordSearched;
    //      }
    //      else{
    //         TempData["error"] = "OOps! no result" + "&#128566" ;
    //      }
    //     return Index();
    // }

    //Get 
    public IActionResult CreateOrder(int id, OrderInfo orderInfo, Meida meida){
        if(id == 0){
            return NotFound();
        }
        var findInDb = _db.Meidas.Find(id);
        if(findInDb == null){
            return NotFound();
        }
        ViewBag.ProductName = meida.ProductName;
        ViewBag.Id = meida.Id;
        ViewBag.Price = meida.Price;

       
        var order = new OrderInfo();
        // var combinedModel = new Tuple<Meida, OrderInfo>(findInDb, orderInfo);


        return View(orderInfo);
    }
    //Post
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateOrderr(OrderInfo orderInfo)
    {
             var media = new Meida();
            //  ViewBag.ProductId = media.Id;
                   
                 try{
                    _db.OrderInfos.Add(orderInfo);
                      await _db.SaveChangesAsync();
                      TempData["success"] = "Your order has been sended!";
                      return RedirectToAction("Index");
          
                 }catch(Exception ex){
                     TempData["error"] = "An Unhandled error, try again";
                     return RedirectToAction("Index");

 
                 }
        
                                

      //  return RedirectToAction("Index");
    }

 
}

Views/CRM/Delete.cshtml
@model Meida
@{
    ViewData["Title"] = "Delete";
}
<br>
<br>
<br>
<br>

<form enctype="multipart/form-data" asp-action="Delete" method="post" >
<input asp-for="Id" hidden>
 @{
       string imageBase64 = Convert.ToBase64String(Model.FileData);
       string imageSrc = $"data:{Model.FileType};base64,{imageBase64}";
   }
 <img width="300" height="300" class="rounded mx-auto d-block" src="@imageSrc" alt="product img">
   
    <input type="file" asp-for="File" id='myfile' disabled class="form-control">
    <label>Current File: </label>
     <span>@Model.Filename</span>

     <span asp-validation-for="FileData" class="text-danger"></span>
     <br>
     <br>
     

        <label asp-for="ProductName"></label>
    <input type="text" asp-for="ProductName" class="form-control" disabled >
     <span asp-validation-for="ProductName" class="text-danger"></span>
       <br>
    <label asp-for="ProductDesc"></label>
    <input type="text" asp-for="ProductDesc" class="form-control" disabled >
     <span asp-validation-for="ProductDesc" class="text-danger"></span>
       <br>
    <label asp-for="Price"></label>
    <input type="number" asp-for="Price" class="form-control"disabled >
     <span asp-validation-for="Price" class="text-danger"></span>
     
     <br>
     <div class="form-group my-4">
        <button type="submit" class="btn btn-outline-danger" >Delete</button>
     </div>

</form>


    var fileValue = '@ViewBag.FileValue';
    
  
    const input = document.querySelector("input[type=file]");
     input.value = fileValue;

</script>
@* <script>

    var fileValue = '@ViewBag.FileValue';
    document.getElementById('myfile').value = fileValue;
</script> *@

Views/CRM/Home.cshtml
@model IEnumerable<Meida>

@{
    ViewData["Title"] = "Home";
}
<br>
<br>
<div class="text-center">
    <h1 class="display-4">Add images for your site</h1>
    <a  role="button" class="btn btn-outline-primary mx-auto"  asp-controller="CRM" asp-action="Upload">Add new image
            <span class="visually-hidden">(current)</span>
          </a>
</div>
<br>
<br>
<h1>Media Index</h1>
<table class="table table-striped  table-hover">
    <thead class="thead-dark">
        <tr> 
            <th   scope="col"> Id</th>
            <th   scope="col" >File Name</th>
            <th   scope="col" >File Type</th>
            <th   scope="col" >File Content</th>
            <th   scope="col" >Product Name</th>
            <th   scope="col">This product for</th>
            <th   scope="col" >Product Description</th>
            <th   scope="col" >Product Price <span>&dollar;</span></th>
            <th   scope="col">Created Time</th>
            <th   scope="col" ></th>
            <th   scope="col" ></th>
           
        </tr>   
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="table-active" style="justify-content: center; align-itmes: center;">
                <th scope="row">
                    @item.Id
                </th>
                <td>
                    @item.Filename
                </td>
                <td>
                    @item.FileType
                </td>
                <td style=" width: 190px">
                    @{
                          string imageBase64 = Convert.ToBase64String(item.FileData);
                          string imageSrc = $"data:{item.FileType};base64,{imageBase64}";
                      }
                    <img width="80" height="70" src="@imageSrc" alt="product img">
                </td>
                <td style="widht: 180px ;">
                    @item.ProductName
                </td>
                <td style="widht: 140px ;">
                    @item.Gender
                </td>
                <td style="min-width: 200px;">
                    @item.ProductDesc
                </td>
                <td style="widht: 100px ;">
                    @item.Price
                </td>
                <td style="widht: 100px ;">
                    @item.CreatedDate
                </td>
                
            
                <td>
                    <a class="btn btn-outline-warning" asp-controller="CRM" asp-action="Update" asp-route-id="@item.Id">Update</a>
                </td>
                <td>
                    <a asp-action="Delete" asp-controller="CRM" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/CRM/Login.cshtml
@model SuperAdmin
@{
    ViewData["Title"] = "Login";
}

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 class="text-center"> Welcome Super Admin</h1>
<br>
<h6 class="text-center text-muted"> Login to check your validation, please</h6>
<form method="post" asp-action="Login">
    <div class="form-group">
      <label asp-for="username" class="form-label mt-4"></label>
      <input type="text" class="form-control" asp-for="username" placeholder="Username" >
      <span  class="form-text text-danger" asp-validation-for="username" ></span>
    </div>
    <div class="form-group">
      <label asp-for="pwd"   class="form-label mt-4">Password</label>
      <input asp-for="pwd" type="password" class="form-control"  placeholder="Password">
      <span  class="form-text text-danger" asp-validation-for="pwd" ></span>
    </div>
     <div class="form-group my-4">
        <button type="submit" class="btn btn-outline-success" >Login</button>
     </div>
    </form>
    @section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/CRM/Update.cshtml
@model Meida
@{
    ViewData["Title"] = "Update";
}

@{
  byte[] fileData = @Model.FileData;
  string base64String = Convert.ToBase64String(fileData);

}
<br>
<br>
<br>
<br>
@if (Model != null && Model.FileData != null)
{

       string imageBase64 = Convert.ToBase64String(Model.FileData);
       string imageSrc = $"data:{Model.FileType};base64,{imageBase64}";
        <img width="300" height="300" src="@imageSrc" id="imagePreview" class="rounded mx-auto d-block" alt="product img">
    
   }

 <br>
<form enctype="multipart/form-data" asp-action="Update" method="post" >

    <div class="text-secondary text-center"></div>
   @* <input type="hidden" asp-for="Filename" value="@Model.Filename" id="filenameInput">
   <input type="hidden" asp-for="FileType" value="@Model.FileType" id="filetypeInput">
   <input type="hidden" asp-for="FileData" value="@Model.FileData" id="filedataInput"> *@
    <input type="file"  id="fileInput"  asp-for="File"    onchange="previewImage(event)" accept="image/*" class="form-control">
  
   
  <br>
     <span asp-validation-for="FileData"  class="text-danger"></span>
     <label asp-for="ProductName"></label>
    <input type="text" asp-for="ProductName" class="form-control"  >
     <span asp-validation-for="ProductName" class="text-danger"></span>
       <br>

    <label asp-for="ProductDesc"></label>
    <input type="text" asp-for="ProductDesc" class="form-control"  >
     <span asp-validation-for="ProductDesc" class="text-danger"></span>
       <br>
    <label asp-for="Price"></label>
    <input type="number" asp-for="Price" class="form-control" >
     <span asp-validation-for="Price" class="text-danger"></span>
     <br>
      <div class="form-group">
      <label asp-for="Gender" class="form-label mt-4" asp-for="Gender">Select Gender : Girl, Boy, or Both</label>
      <select asp-for="Gender" class="form-select" id="genderSelection">
        <option  asp-for="Gender" value="Girl">Girl</option>
        <option  asp-for="Gender" value="Boy">Boy</option>
        <option  asp-for="Gender" value="Both">Both</option>
      </select>
      <span asp-validation-for="Gender" class="text-danger"></span>
    </div>
     
     
     <br>
      <div class="form-group my-4">
        <button type="submit" class="btn btn-outline-warning" >Update</button>
     </div>

</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

@if (Model != null && Model.FileData != null)
{
    <script>
        const fileInput = document.querySelector('input[type="file"]');
        var base64String = '@Html.Raw(base64String)'; // Ensure proper rendering of the C# base64String

        var binaryString = atob(base64String);

        // Create a new Uint8Array from the binary string
        const byteArray = new Uint8Array(binaryString.length);
        for (let i = 0; i < binaryString.length; i++) {
            byteArray[i] = binaryString.charCodeAt(i);
        }

        // Create a new Blob from the byte array
        const blob = new Blob([byteArray]);

        // Create a new File object for the image
        const myFile = new File([blob], '@Model.Filename', {
            type: '@Model.FileType',
            lastModified: new Date(),
        });

        // Now let's create a DataTransfer to get a FileList
        const dataTransfer = new DataTransfer();
        dataTransfer.items.add(myFile);
        fileInput.files = dataTransfer.files;
    </script>
}
<!--
  var base64String = 'SGVsbG8gd29ybGQh'; // Base64-encoded string
var decodedString = atob(base64String);

console.log(decodedString); // Output: Hello world!

   //  var arrayBuffer = this.result, array = new Uint8Array(arrayBuffer), binaryString = String.fromCharCode.apply(null,array);
 
  A Blob is an opaque reference to, or handle for, a chunk of data. The name comes from SQL databases, where it means “Binary Large Object.” In JavaScript, Blobs often represent binary data, and they can be large, but neither is required: a Blob could also represent the contents of a small text file.
-->
<script>
 function previewImage(event) {
    var input = event.target;
    var reader = new FileReader();

    reader.onload = function () {
        var img = document.getElementById("imagePreview");
        img.src = reader.result;
       // img.style.display = "";
    };

    reader.readAsDataURL(input.files[0]);
}

</script>

@* 
<input type="file" id="fileInput" name="File" />

<script>
    // Get a reference to our file input
    const fileInput = document.getElementById('fileInput');

    // Set the value of the file input to the filename
    fileInput.value = '@filename';

    // Add an event listener to handle file selection
    fileInput.addEventListener('change', function (event) {
        const selectedFile = event.target.files[0];
        
        // Create a new FileReader instance
        const reader = new FileReader();

        // Handle the file load event
        reader.onload = function (loadEvent) {
            const arrayBuffer = loadEvent.target.result;
            
            // Create a new File object for the image
            const myFile = new File([arrayBuffer], selectedFile.name, { type: selectedFile.type, lastModified: selectedFile.lastModified });

            // Now let's create a DataTransfer to get a FileList
            const dataTransfer = new DataTransfer();
            dataTransfer.items.add(myFile);
            fileInput.files = dataTransfer.files;
        };

        // Read the file as an ArrayBuffer
        reader.readAsArrayBuffer(selectedFile);
    });
</script> *@

Views/CRM/Upload.cshtml
@model Meida
@{
    ViewData["Title"] = "Upload";
}


<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-md-6">
        <div class="class="rounded mx-auto d-block"">
            your img
            <img src="#" width="300" height="300"  id="imagePreview" style="display: none;">

        </div>
    </div>
</div>

<form enctype="multipart/form-data" method="post" >
     <label asp-for="File"></label>
    <input type="file" asp-for="File" class="form-control" onchange="previewImage(event)" accept="image/*">
     <span asp-validation-for="FileData" class="text-danger"></span>
     <br>
    <label asp-for="ProductName"></label>
    <input type="text" asp-for="ProductName" class="form-control"  >
     <span asp-validation-for="ProductName" class="text-danger"></span>
       <br>

    <label asp-for="ProductDesc"></label>
    <input type="text" asp-for="ProductDesc" class="form-control"  >
     <span asp-validation-for="ProductDesc" class="text-danger"></span>
       <br>
    <label asp-for="Price"></label>
    <input type="number" asp-for="Price" class="form-control"  >
     <span asp-validation-for="Price" class="text-danger"></span>
     <br>
      <div class="form-group">
      <label asp-for="Gender" class="form-label mt-4" asp-for="Gender">Select Gender : Girl, Boy, or Both</label>
      <select asp-for="Gender" class="form-select" id="genderSelection">
        <option  asp-for="Gender" value="Girl">Girl</option>
        <option  asp-for="Gender" value="Boy">Boy</option>
        <option  asp-for="Gender" value="Both">Both</option>
      </select>
      <span asp-validation-for="Gender" class="text-danger"></span>
    </div>
     
     <br>
     <div class="form-group my-4">
    <input class="btn btn-outline-primary" type="submit" >
         
     </div>

</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}


<script>
    function previewImage(event) {
    var input = event.target;
    var reader = new FileReader();

    reader.onload = function () {
        var img = document.getElementById("imagePreview");
        img.src = reader.result;
        img.style.display = "";
    };

    reader.readAsDataURL(input.files[0]);
}

</script>